import os
import subprocess
import datetime

WORKSPACE = "/home/pipin201305/.openclaw/workspace"
KST = datetime.timezone(datetime.timedelta(hours=9))

def run_script(script_name):
    try:
        result = subprocess.run(["python3", os.path.join(WORKSPACE, "scripts", script_name)], capture_output=True, text=True)
        return result.stdout
    except Exception as e:
        return f"실행 오류: {e}"

def update_dashboard():
    now_kst = datetime.datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S")
    
    print("대시보드 데이터를 수집 중입니다...")
    emails = run_script("fetch_emails.py")
    cal = run_script("fetch_calendar.py")
    news = run_script("fetch_news.py")
    
    md_content = f"""# 📊 박비서 통합 대시보드
**최종 업데이트:** {now_kst} (KST)

> 💡 *OpenClaw Web UI에서 이 문서를 클릭하시면 깔끔하게 렌더링된 화면으로 보실 수 있습니다. (박비서가 백그라운드에서 주기적으로 최신화합니다.)*

---

## 📬 1. 우편함 브리핑 (최근 24시간)
```text
{emails.strip()}
```

## 📅 2. 다가오는 주요 일정
```text
{cal.strip()}
```

## 📰 3. 오늘의 경제/부동산 뉴스 (Top 5)
```text
{news.strip()}
```

---
*Generated by OpenClaw Assistant (박비서)*
"""
    
    with open(os.path.join(WORKSPACE, "DASHBOARD.md"), "w") as f:
        f.write(md_content)
    print("✅ DASHBOARD.md 업데이트 완료.")

if __name__ == "__main__":
    update_dashboard()
